-- Execute este script no SQL Editor do seu painel do Supabase

-- ==== TABELAS ====

-- Tabela de Policiais / Membros
CREATE TABLE IF NOT EXISTS members (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ordem INTEGER NOT NULL,
  matricula TEXT NOT NULL UNIQUE,
  cpf TEXT NOT NULL UNIQUE,
  patente TEXT NOT NULL,
  nome TEXT NOT NULL,
  guerra TEXT NOT NULL,
  funcao TEXT NOT NULL,
  telefone TEXT,
  email TEXT,
  status TEXT NOT NULL,
  pdf_name TEXT,
  pdf_url TEXT,
  photo_url TEXT,
  quadro TEXT,
  rg_militar TEXT,
  data_emissao_rg TEXT,
  comportamento TEXT,
  vinculo TEXT,
  data_nascimento TEXT,
  cidade_nascimento TEXT,
  uf_nascimento TEXT,
  pasep TEXT,
  reg_civil TEXT,
  pai TEXT,
  mae TEXT,
  tipo_sanguineo TEXT,
  fator_rh TEXT,
  data_inclusao TEXT
);

-- Tabela de Audiências
CREATE TABLE IF NOT EXISTS audiencias (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data TEXT NOT NULL,
  hora TEXT NOT NULL,
  local TEXT NOT NULL,
  processo TEXT NOT NULL,
  status TEXT NOT NULL,
  observacoes TEXT
);

-- Relação Policiais x Audiências (N-N)
CREATE TABLE IF NOT EXISTS audiencia_membros (
  audiencia_id INTEGER REFERENCES audiencias(id) ON DELETE CASCADE,
  member_id INTEGER REFERENCES members(id) ON DELETE CASCADE,
  PRIMARY KEY (audiencia_id, member_id)
);

-- PDFs de Audiências
CREATE TABLE IF NOT EXISTS audiencia_pdfs (
  id TEXT PRIMARY KEY,
  audiencia_id INTEGER REFERENCES audiencias(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL
);

-- Tabela de Notificações
CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY,
  member_id INTEGER REFERENCES members(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  date TEXT NOT NULL,
  read BOOLEAN NOT NULL DEFAULT FALSE
);

-- Tabela de Anexos
CREATE TABLE IF NOT EXISTS anexos (
  id TEXT PRIMARY KEY,
  member_id INTEGER REFERENCES members(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT NOT NULL,
  date TEXT NOT NULL,
  size INTEGER
);

-- Tabela de Ocorrências
CREATE TABLE IF NOT EXISTS ocorrencias (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  tipo TEXT NOT NULL,
  local TEXT NOT NULL,
  descricao TEXT,
  status TEXT NOT NULL DEFAULT 'Em andamento',
  policial_relator_id INTEGER REFERENCES members(id)
);

-- Tabela de Metas
CREATE TABLE IF NOT EXISTS metas (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  titulo TEXT NOT NULL,
  descricao TEXT,
  valor_alvo NUMERIC NOT NULL,
  valor_atual NUMERIC NOT NULL DEFAULT 0,
  unidade TEXT NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  categoria TEXT NOT NULL
);

-- Tabela de Logística
CREATE TABLE IF NOT EXISTS logistica (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item TEXT NOT NULL,
  prefixo TEXT,
  status TEXT NOT NULL,
  ultima_revisao DATE,
  proxima_revisao DATE,
  responsavel_id INTEGER REFERENCES members(id)
);

-- ==== HABILITAR RLS ====
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE audiencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE audiencia_membros ENABLE ROW LEVEL SECURITY;
ALTER TABLE audiencia_pdfs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE anexos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ocorrencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE metas ENABLE ROW LEVEL SECURITY;
ALTER TABLE logistica ENABLE ROW LEVEL SECURITY;

-- ==== POLÍTICAS ANONIMAS PARA DESENVOLVIMENTO ====
CREATE POLICY "Public Access members" ON members FOR ALL USING (true);
CREATE POLICY "Public Access audiencias" ON audiencias FOR ALL USING (true);
CREATE POLICY "Public Access audiencia_membros" ON audiencia_membros FOR ALL USING (true);
CREATE POLICY "Public Access audiencia_pdfs" ON audiencia_pdfs FOR ALL USING (true);
CREATE POLICY "Public Access notifications" ON notifications FOR ALL USING (true);
CREATE POLICY "Public Access anexos" ON anexos FOR ALL USING (true);
CREATE POLICY "Public Access ocorrencias" ON ocorrencias FOR ALL USING (true);
CREATE POLICY "Public Access metas" ON metas FOR ALL USING (true);
CREATE POLICY "Public Access logistica" ON logistica FOR ALL USING (true);

-- ==== BUCKET DE ARMAZENAMENTO ====
-- Criação do bucket para os documentos caso não exista
INSERT INTO storage.buckets (id, name, public) VALUES ('documentos', 'documentos', true) ON CONFLICT DO NOTHING;

-- Políticas de segurança para o bucket 'documentos'
-- Leitura: Permite que qualquer pessoa veja os arquivos (necessário para getPublicUrl se o bucket for público)
CREATE POLICY "Leitura pública de documentos" ON storage.objects FOR SELECT USING (bucket_id = 'documentos');

-- Inserção: Restrito a usuários autenticados para evitar abusos no armazenamento
CREATE POLICY "Upload restrito a usuários autenticados" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'documentos');

-- Deleção: Restrito a usuários autenticados
CREATE POLICY "Deleção restrita a usuários autenticados" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'documentos');
